/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
'use client'
import { type FC, useMemo, useRef } from 'react'
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    [key: string]: THREE.Mesh
  }
  materials: {
    default?: THREE.MeshStandardMaterial
  }
}

type Props = React.ComponentProps<'group'>

const GemModel: FC<Props> = ({ ...props }) => {
  const groupRef = useRef<THREE.Group>(null!)
  const { nodes } = useGLTF('/models/gem.gltf') as unknown as GLTFResult

  const firstNode = nodes.scene || nodes[Object.keys(nodes)[0]]

  const material = useMemo(() => {
    const baseColor = new THREE.Color(0x37d6c7) // teal-accent
    const emissiveColor = new THREE.Color(0x37d6c7)

    return new THREE.MeshPhysicalMaterial({
      color: baseColor,
      metalness: 0.05,
      roughness: 0.05,
      emissive: emissiveColor,
      emissiveIntensity: 0.95,
      envMapIntensity: 1.5,
      clearcoat: 1.0,
      clearcoatRoughness: 0.02,
      reflectivity: 1.0,
      ior: 1.6,
      transmission: 0.0,
      thickness: 0.5,
      transparent: true,
      opacity: 0.8,
    })
  }, [])

  // Clone and apply material
  const clonedNode = useMemo(() => {
    const cloned = firstNode.clone()
    cloned.traverse((child) => {
      if (child instanceof THREE.Mesh) {
        child.material = material
        child.castShadow = true
        child.receiveShadow = true

        // Check if vertex colors exist and remove them
        if (child.geometry.attributes.color) {
          child.geometry.deleteAttribute('color')
        }
      }
    })
    return cloned
  }, [firstNode, material])

  useFrame((_, delta) => {
    if (groupRef.current) {
      groupRef.current.rotation.z += delta * 1
    }
  })

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={clonedNode} />
      </group>
    </group>
  )
}

export default GemModel

useGLTF.preload('/models/gem.gltf')
